version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: fleet_db
    restart: always
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
  
  web:
    build:
      context: ./src/api
    container_name: django_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"