# Generated by Django 5.1.6 on 2025-02-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('make', models.CharField()),
                ('year', models.IntegerField()),
                ('color', models.CharField()),
                ('category', models.CharField()),
                ('engine_type', models.CharField()),
                ('seats', models.IntegerField(default=0)),
                ('transmission', models.CharField()),
                ('top_speed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car_api.model')),
            ],
        ),
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub Model', models.CharField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_api.car')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='sub_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_models', to='car_api.submodel'),
        ),
    ]
