# Generated by Django 5.1.6 on 2025-02-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0002_car_created_at_car_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submodel',
            name='car',
        ),
        migrations.AddField(
            model_name='make',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='makes', to='car_api.car'),
            preserve_default=False,
        ),
    ]
