# Generated by Django 5.1.6 on 2025-02-16 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0003_remove_submodel_car_make_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make',
            name='car',
        ),
        migrations.RemoveField(
            model_name='make',
            name='model',
        ),
        migrations.RemoveField(
            model_name='model',
            name='sub_model',
        ),
        migrations.AddField(
            model_name='car',
            name='sub_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_api.submodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='make',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='make',
            name='name',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='make',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='model',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='model',
            name='make',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car_api.make'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submodel',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_models', to='car_api.model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
