# Generated by Django 5.1.6 on 2025-02-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0005_alter_car_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='Model',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='submodel',
            name='Sub Model',
            field=models.CharField(unique=True),
        ),
    ]
