# Generated by Django 5.1.6 on 2025-02-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0006_alter_make_name_alter_model_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='Model',
            new_name='name',
        ),
    ]
