# Generated by Django 5.1.6 on 2025-02-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0007_rename_model_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submodel',
            old_name='Sub Model',
            new_name='name',
        ),
    ]
