# Generated by Django 5.1.6 on 2025-02-16 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0008_rename_sub_model_submodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car_api.model'),
            preserve_default=False,
        ),
    ]
